window:
  padding:
    x: 20
    y: 20

font:
  normal:
    family: Fira Code
  bold: 
    family: Fira Code
  italic: 
    family: Fira Code
  size: 14
  offset:
    x: 0
    y: 0

window.dynamic_title: false
background_opacity: 0.9
draw_bold_text_with_bright_colors: true

debug:
  render_timer: false
  persistent_logging: false
  log_level: OFF
  print_events: false
  ref_test: false

colors:
  primary:
    background: '#111111'
    foreground: '#f8f8f2'

  cursor:
    text: '#f8f8f2'
    cursor: '#111111'

  normal:
    black:   '#3c3d37'
    red:     '#f92672'
    green:   '#a6e22e'
    blue:    '#66d9ef'
    cyan:    '#66d9ef'
    magenta: '#ae81ff'
    white:   '#f8f8f2'
    yellow:  '#e6db74'

  bright:
    black:   '#3c3d37'
    red:     '#f92672'
    green:   '#a6e22e'
    blue:    '#66d9ef'
    cyan:    '#66d9ef'
    magenta: '#ae81ff'
    white:   '#f8f8f2'
    yellow:  '#e6db74'
