window:
  padding:
    x: 15
    y: 15

font:
  normal:
    family: Monofur Nerd Font Mono
  bold:
    family: Monofurbold Nerd Font Mono
  italic:
    family: Monofuritalic Nerd Font Mono
  size: 16
  offset:
    x: 0
    y: 1

window.dynamic_title: false
background_opacity: 1
draw_bold_text_with_bright_colors: true

debug:
  render_timer: false
  persistent_logging: false
  log_level: OFF
  print_events: false
  ref_test: false

colors:
  # Default colors
  primary:
    background: '#0F1419'
    foreground: '#FAFAFA'
    bright_foreground: '#F07178'

  # Normal colors
  normal:
    black:   '#212733'
    red:     '#F07178'
    green:   '#B8CC52'
    yellow:  '#FFC44C'
    blue:    '#80D4FF'
    magenta: '#A37ACC'
    cyan:    '#95E6CB'
    white:   '#FAFAFA'

  # Brightened
  bright:
    black: '#D9D8D7'
    red: '#F07178'
    green: '#BBE67E'
    yellow: '#FFD57F'
    blue: '#95E6CB'
    magenta: '#D4BFFF'
    cyan: '#95E6CB'
    white: '#FFFFFF'

  # Cursor colors
  cursor:
    text:   '#2D3640'
    cursor: '#9CA1AA'

  # Selection colors
  selection:
    text:       '#080808'
    background: '#b2ceee'
