window:
  padding:
    x: 20
    y: 20

font:
  normal:
    family: Fantasque Sans Mono
  bold:
    family: Fantasque Sans Mono
  italic:
    family: Fantasque Sans Mono
  size: 16
  offset:
    x: 0
    y: 1

window.dynamic_title: false
background_opacity: 0.9
draw_bold_text_with_bright_colors: true

debug:
  render_timer: false
  persistent_logging: false
  log_level: OFF
  print_events: false
  ref_test: false

colors:
  primary:
    background: '#002222'
    foreground: '#ddccaa'

  cursor:
    text: '#554444'
    cursor: '#ddccaa'

  normal:
    black:   '#665555'
    red:     '#cc2222'
    green:   '#999911'
    yellow:  '#dd9922'
    blue:    '#448888'
    magenta: '#dd8888'
    cyan:    '#88cccc'
    white:   '#ffffcc'

  bright:
    black:   '#776666'
    red:     '#ff4444'
    green:   '#bbbb22'
    yellow:  '#ffbb22'
    blue:    '#88aa99'
    magenta: '#dd8899'
    cyan:    '#88cc77'
    white:   '#ddccaa'
