window:
  padding:
    x: 20
    y: 20

font:
  normal:
    family: agave Nerd Font Mono
  bold:
    family: agave Nerd Font Mono
  italic:
    family: agave Nerd Font Mono
  size: 16
  offset:
    x: 0
    y: 1

window.dynamic_title: false
background_opacity: 0.98
draw_bold_text_with_bright_colors: true

debug:
  render_timer: false
  persistent_logging: false
  log_level: OFF
  print_events: false
  ref_test: false

colors:
  # Default colors
  primary:
    background: '#0f1315'
    foreground: '#C5C8C9'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '#d6d6d6'
    cursor: '#303435'

  # Normal colors
  normal:
    black:   '#303435'
    red:     '#e74c4c'
    green:   '#6bb05d'
    yellow:  '#e59e67'
    blue:    '#5b98a9'
    magenta: '#ef7cbb'
    cyan:    '#51a39f'
    white:   '#c4c4c4'

  # Bright colors
  bright:
    black:   '#3a3c3d'
    red:     '#c26f6f'
    green:   '#8dc776'
    yellow:  '#e7ac7e'
    blue:    '#7ab3c3'
    magenta: '#d3869b'
    cyan:    '#6db0ad'
    white:   '#bfbfbf'
