window:
  padding:
    x: 20
    y: 20

font:
  normal:
    family: CozetteVector
  bold:
    family: CozetteVector
  italic:
    family: CozetteVector
  size: 20
  offset:
    x: 0
    y: 1

window.dynamic_title: false
background_opacity: 0.9
draw_bold_text_with_bright_colors: true

debug:
  render_timer: false
  persistent_logging: false
  log_level: OFF
  print_events: false
  ref_test: false

colors:
  primary:
    background: '0x121212'
    foreground: '0xdfbf8e'

  cursor:
    text: '#f8f8f2'
    cursor: '#111111'

  normal:
    black:   '0x665c54'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe78a4e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

  bright:
    black:   '0x928374'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe3a84e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'
