window:
  padding:
    x: 18
    y: 20

font:
  normal:
    family: agave Nerd Font Mono
  bold:
    family: agave Nerd Font Mono
  italic:
    family: agave Nerd Font Mono
  size: 14
  offset:
    x: 0
    y: 1

window.dynamic_title: false
background_opacity: 1
draw_bold_text_with_bright_colors: true

debug:
  render_timer: false
  persistent_logging: false
  log_level: OFF
  print_events: false
  ref_test: false

colors:
  # Default colors
  primary:
    background: '#282828'
    foreground: '#f9f5d7'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '#f9f5d7'
    cursor: '#3c3836'

  # Normal colors
  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#689d6a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#076678'
    white:   '#f9f5d7'

  # Bright colors
  bright:
    black:   '#32302f'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#458588'
    white:   '#f9f5d7'
